networks:
  tangledhub:


volumes:
  mysql-data:


services:
  db:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_TCP_PORT=${DB_PORT}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tangledhub

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - PORT=${API_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MIKRO_ORM_TYPE=${DB_DRIVER}
      - MIKRO_ORM_USER=${DB_USER}
      - MIKRO_ORM_PASSWORD=${DB_PASS}
      - MIKRO_ORM_HOST=db # name of database service
      - MIKRO_ORM_PORT=${DB_PORT}
      - MIKRO_ORM_DB_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - tangledhub

  web:
    build:
      context: ./www
      dockerfile: Dockerfile.dev
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      - WEB_PORT=${WEB_PORT}
    volumes:
      - ./www/src:/www/src:ro
    networks:
      - tangledhub
